### ISSUE TITLE
After The Update it stopped working.

### ISSUE THREAD

**Issue by Jonaz1** [Nanite-Construction-System/NaniteConstructionSystem#108]
After The Update it stopped working, hopfully it will be fixed. It only glows Red and doesnt show anything on the right were the scanned blocks and stream and all that should be. Cant live without it!
Thanks a Lot!

**Comment by JetsetQuasar** [comment]
Can confirm. Nanite machine is broken

**Comment by tryst46** [comment]
Not sure about the update because I just got it, but it IS broken.

It worked fine while I had a small(ish) base. But when it got to over 10K blocks, the nanites seemed to work for a while, then got confused and went on strike. If your autosave is on, it also caused the autosave to fail to report a sucessful save. This means you can't even exit and reload without using task manager to force it to shut down.

Checked the PC's CPU and it the meter said it was using well over 98% of my processing power and it just stayed there without moving. The control centre said it was calculating blocks which it did SLOWLY and the construction nanites had 6 targets but no nanites were being sent out.

**Comment by Seldion** [comment]
So I can also confirm that as of 2 patches ago, not the frost bite one, this mod freezes the game, it only freezes it when deconstructing something, before the last two patches it worked fine for me, I only used this mod, constructing, mining, gathering items and healing all work but once I start to deconstruct something it freezes and I have to end task it.
